#docker-compose -f docker-compose.yml up
version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=AUTHENTICATION
      - MYSQL_ROOT_PASSWORD=root_pw
